steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/microservices-academy/images-hadyi/frontend-academy",
        "-f",
        "Dockerfile.prod",
        "--platform=linux/amd64",
        "--build-arg",
        "GATEWAY_URL=http://35.202.115.135:3000",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/microservices-academy/images-hadyi/frontend-academy",
      ]

options:
  logging: CLOUD_LOGGING_ONLY
