# 1. Dependencias

FROM node:20-alpine AS deps

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm ci

# 2. Build

FROM node:20-alpine AS build

WORKDIR /usr/src/app

COPY --from=deps /usr/src/app/node_modules ./node_modules

COPY . .

RUN npm run build

# 3. Prod

FROM node:20-alpine AS prod

WORKDIR /usr/src/app

ENV NODE_ENV=production
ENV PORT=3004

# standalone genera server.js y solo lo necesario de node_modules
COPY --from=build /usr/src/app/.next/standalone ./

# standalone no incluye static por defecto, hay que copiarlo aparte
COPY --from=build /usr/src/app/.next/static ./.next/static

# copiar archivos públicos si existen
COPY --from=build /usr/src/app/public ./public

EXPOSE 3004

CMD ["node", "server.js"]
